services:
  db:
    image: postgres:16-alpine
    container_name: matchme_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-matchme_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-matchme_pass}
      POSTGRES_DB: ${POSTGRES_DB:-matchme_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-matchme_user} -d ${POSTGRES_DB:-matchme_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: matchme_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  api:
    build: .
    container_name: matchme_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data: